export const logosConfig = {
	"encancha": {
		alt: "En Cancha",
		href: "/",
		width: "146",
		height: "22",
		ampWidth: "215",
		ampHeight: "33",
		title: "En Cancha",
		variants: {
			default: { path: "/resources/logos/encancha.svg" },
		},
	},
	"enlahora": {
		alt: "En La Hora",
		href: "/enlahora",
		width: "146",
		height: "40",
		ampWidth: "215",
		ampHeight: "59",
		title: "En La Hora | En Cancha",
		variants: {
			default: { path: "/resources/logos/en-la-hora.svg" },
		},
	},
	"en-la-hora": {
		alt: "En La Hora",
		href: "/en-la-hora",
		width: "146",
		height: "40",
		ampWidth: "215",
		ampHeight: "59",
		title: "En La Hora | En Cancha",
		variants: {
			default: { path: "/resources/logos/en-la-hora.svg" },
		},
	},
	"tiempo-x": {
		alt: "Tiempo X",
		href: "/tiempo-x",
		width: "146",
		height: "40",
		ampWidth: "215",
		ampHeight: "59",
		title: "Tiempo X | En Cancha",
		variants: {
			default: { path: "/resources/logos/tiempo-x.svg" },
		},
	},
	"tiempox": {
		alt: "Tiempo X",
		href: "/tiempox",
		width: "146",
		height: "40",
		ampWidth: "215",
		ampHeight: "59",
		title: "Tiempo X | En Cancha",
		variants: {
			default: { path: "/resources/logos/tiempo-x.svg" },
		},
	},
	"tecno-game": {
		href: "/tecno-game",
		width: "146",
		height: "40",
		ampWidth: "215",
		ampHeight: "59",
		title: "Tecno Game | En Cancha",
		variants: {
			default: { path: "/resources/logos/tecno-game.svg" },
		},
	},
	"tribuna-andes": {
		alt: "Tribuna Andes",
		href: "/tribuna-andes",
		width: "131",
		height: "46",
		ampWidth: "193",
		ampHeight: "68",
		title: "Tribuna Andes | En Cancha",
		variants: {
			default: { path: "/resources/logos/tribuna-andes.svg" },
		},
	},
	"motor": {
		alt: "Motor",
		href: "/motor",
		width: "146",
		height: "40",
		ampWidth: "215",
		ampHeight: "59",
		title: "Motor | En Cancha",
		variants: {
			default: { path: "/resources/logos/motor-modal.svg" },
		},
	},
	"prime": {
		alt: "Prime",
		href: "/prime",
		width: "150",
		height: "40",
		ampWidth: "221",
		ampHeight: "59",
		title: "Prime | En Cancha",
		variants: {
			default: { path: "/resources/logos/prime.svg" },
		},
	},
	"podcast": {
		alt: "En Cancha",
		href: "/",
		width: "146",
		height: "22",
		ampWidth: "215",
		ampHeight: "33",
		title: "En Cancha",
		variants: {
			default: { path: "/resources/logos/encancha-bco.svg" },
			modal: { path: "/resources/logos/encancha.svg" },
		},
	},
	"videos": {
		alt: "En Cancha",
		href: "/",
		width: "146",
		height: "22",
		ampWidth: "215",
		ampHeight: "33",
		title: "En Cancha",
		variants: {
			default: { path: "/resources/logos/encancha-bco.svg" },
			modal: { path: "/resources/logos/encancha.svg" },
		},
	},
	"latfan": {
		alt: "Latfan",
		href: "/",
		width: "227",
		height: "50",
		ampWidth: "150",
		ampHeight: "33",
		title: "Latfan",
		variants: {
			default: { path: "/resources/logos/latfan.svg" },
		},
	},
};
